# Form implementation generated from reading ui file 'metmessage.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

selected_format = 0
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(251, 233)
        Dialog.setWindowIcon(QtGui.QIcon("Images/M.png"))
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 180, 211, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.radioButton = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton.setGeometry(QtCore.QRect(50, 20, 151, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 60, 151, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 60, 151, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.setDisabled(True)
        self.radioButton_3.hide()
        self.radioButton_3.setChecked(True)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(50, 140, 151, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_5.setGeometry(QtCore.QRect(50, 100, 151, 20))
        self.radioButton_5.setObjectName("radioButton_5")


        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        ok_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        ok_button.clicked.connect(self.select_format)

        self.radioButton.setChecked(False)
        self.radioButton_2.setChecked(False)

        def close_dialog():
            global selected_format
            selected_format = 0
            Dialog.close()

        cancel_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        cancel_button.clicked.connect(close_dialog)

    def select_format(self):
        global selected_format
        if self.radioButton.isChecked() == True:
            selected_format = 1
        elif self.radioButton_2.isChecked() == True:
            selected_format = 2
        elif self.radioButton_4.isChecked() == True:
            selected_format = 3
        elif self.radioButton_5.isChecked() == True:
            selected_format = 4
        elif self.radioButton_3.isChecked() == True:
            selected_format = 0

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select MET Format"))
        self.radioButton.setText(_translate("Dialog", "Create METCM Message"))
        self.radioButton_2.setText(_translate("Dialog", "Create METTA Message"))
        self.radioButton_4.setText(_translate("Dialog", "All Types - All Files"))
        self.radioButton_5.setText(_translate("Dialog", "Create METAV Message"))

class MyDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

    def closeEvent(self, event):
        global selected_format
        selected_format = 0
        event.accept()


def open_met_dialog():
    Dialog = MyDialog()
    Dialog.setStyle(QtWidgets.QStyleFactory.create("Windows Vista"))
    Dialog.show()
    Dialog.exec()